"""
Define All Immutable Variables
"""
"""

"""
PYSPARK_RUN_METHOD: str = "transform"
PLEASE_CHECK_CONFIGURATION: str = "Please Check Configuration"
"""
Node For Environment Variables
"""
ENV_VAR_CONFIG_FILE_PATH: str = "CONFIG_FILE_PATH"
ENV_VAR_REGION: str = "REGION"
ENV_VAR_CONFIG_READER_SOURCE: str = "CONFIG_READER_SOURCE"
"""
Config Node Constants for Overall Process
"""
NODE_CONFIG_READER_SOURCE: str = "config_reader_source"
NODE_AWS_REGION: str = "aws_region"
NODE_ENVIRONMENT: str = "environment"
NODE_PROCESSOR_TYP: str = "processor_typ"
NODE_LOGGER_NAME: str = "logger_name"
"""
Config Node Constants for Metric Module
"""
NODE_METRIC_FLUSH_INTERVAL: str = "flush_interval"
NODE_METRIC_FLUSH_BATCH_SIZE: str = "flush_batch_size"
"""
Config Node Constants for Reader Module
"""
NODE_INPUT_READER_TYP: str = "reader_typ"
NODE_INPUT_FORMAT: str = "format"
NODE_INPUT_SCHEMA: str = "schema"
NODE_INPUT_SOURCE_PATH: str = "sourcePath"
NODE_INPUT_FILE_PATTERN: str = "filePattern"
NODE_INPUT_FORMAT_OPTIONS: str = "format_options"
NODE_INPUT_KAFKA_SECRET_NAME: str = "secret_name"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_BOOTSTRAP_SERVER: str = "kafka.bootstrap.servers"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_SECURITY_PROTOCOL: str = "kafka.security.protocol"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_SOURCE_TOPIC: str = "subscribe"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_SECRET_KEY_STORE_JKS: str = "kafka.ssl.keystore.location"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_SECRET_KEY_STORE_PASSWORD: str = "kafka.ssl.keystore.password"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_SECRET_TRUST_STORE_JKS: str = "kafka.ssl.truststore.location"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_SECRET_TRUST_STORE_PASSWORD: str = "kafka.ssl.truststore.password"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_SECRET_SSL_KEY_PASSWORD: str = "kafka.ssl.key.password"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_SECRET_STARTING_OFFSET: str = "startingOffsets"
NODE_INPUT_FORMAT_OPTIONS_KAFKA_SECRET_FAIL_ON_DATA_LOSS: str = "failOnDataLoss"
"""
Generated Key Constants for Reader Module
"""
NODE_INPUT_GEN_READER_OPTIONS: str = "reader_options"
NODE_INPUT_GEN_SPARK: str = "spark"
NODE_INPUT_GEN_FORMAT: str = "format"
NODE_INPUT_GEN_OPTIONS: str = "options"
NODE_INPUT_GEN_SCHEMA: str = "schema"
NODE_INPUT_GEN_PATH: str = "path"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_BOOTSTRAP_SERVER: str = "kafka.bootstrap.servers"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_SECURITY_PROTOCOL: str = "kafka.security.protocol"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_SOURCE_TOPIC: str = "subscribe"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_KEY_STORE_JKS: str = "kafka.ssl.keystore.location"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_KEY_STORE_PASSWORD: str = "kafka.ssl.keystore.password"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_TRUST_STORE_JKS: str = "kafka.ssl.truststore.location"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_TRUST_STORE_PASSWORD: str = "kafka.ssl.truststore.password"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_SSL_KEY_PASSWORD: str = "kafka.ssl.key.password"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_STARTING_OFFSET: str = "startingOffsets"
NODE_INPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_FAIL_ON_DATA_LOSS: str = "failOnDataLoss"
"""
Boolean Variables Constants
"""
STRING_TRUE: str = "true"
STRING_FALSE: str = "false"
BOOLEAN_TRUE: bool = True
BOOLEAN_FALSE: bool = False
"""
Config Node Constants for Writer Module
"""
NODE_OUTPUT_WRITER_TYP: str = "writer_typ"
NODE_OUTPUT_TARGET_PATH: str = "targetPath"
NODE_OUTPUT_FORMAT: str = "format"
NODE_OUTPUT_PARTITION_BY: str = "partitionBy"
NODE_OUTPUT_OUTPUT_MODE: str = "outputMode"
NODE_OUTPUT_KAFKA_SECRET_NAME: str = "secret_name"
NODE_OUTPUT_WRITER_TYP_OPTIONS: str = "writer_typ_options"
NODE_OUTPUT_STREAM_OPTIONS: str = "stream_options"
NODE_OUTPUT_FORMAT_OPTIONS_KAFKA_BOOTSTRAP_SERVER: str = "kafka.bootstrap.servers"
NODE_OUTPUT_FORMAT_OPTIONS_KAFKA_SECURITY_PROTOCOL: str = "kafka.security.protocol"
NODE_OUTPUT_FORMAT_OPTIONS_KAFKA_SOURCE_TOPIC: str = "topic"
NODE_OUTPUT_FORMAT_OPTIONS_KAFKA_SECRET_KEY_STORE_JKS: str = "kafka.ssl.keystore.location"
NODE_OUTPUT_FORMAT_OPTIONS_KAFKA_SECRET_KEY_STORE_PASSWORD: str = "kafka.ssl.keystore.password"
NODE_OUTPUT_FORMAT_OPTIONS_KAFKA_SECRET_TRUST_STORE_JKS: str = "kafka.ssl.truststore.location"
NODE_OUTPUT_FORMAT_OPTIONS_KAFKA_SECRET_TRUST_STORE_PASSWORD: str = "kafka.ssl.truststore.password"
NODE_OUTPUT_FORMAT_OPTIONS_KAFKA_SECRET_SSL_KEY_PASSWORD: str = "kafka.ssl.key.password"
NODE_OUTPUT_FORMAT_OPTIONS_KAFKA_SECRET_STARTING_OFFSET: str = "startingOffsets"
"""
Generated Key Constants for Writer Module
"""
NODE_OUTPUT_GEN_WRITER_TYP: str = "writer_typ"
NODE_OUTPUT_GEN_WRITER_ALL_OPTIONS: str = "writer_all_options"
NODE_OUTPUT_GEN_WRITE_FORMAT: str = "write_format"
NODE_OUTPUT_GEN_WRITE_OPTIONS: str = "write_options"
NODE_OUTPUT_GEN_TARGET_PATH: str = "target_path"
NODE_OUTPUT_GEN_PARTITION_BY: str = "partition_by"
NODE_OUTPUT_GEN_OUTPUT_MODE: str = "output_mode"
NODE_OUTPUT_GEN_STREAM_OPTIONS: str = "stream_options"
NODE_OUTPUT_FORMAT_GEN_OPTIONS_KAFKA_BOOTSTRAP_SERVER: str = "kafka.bootstrap.servers"
NODE_OUTPUT_FORMAT_GEN_OPTIONS_KAFKA_SECURITY_PROTOCOL: str = "kafka.security.protocol"
NODE_OUTPUT_FORMAT_GEN_OPTIONS_KAFKA_SOURCE_TOPIC: str = "topic"
NODE_OUTPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_KEY_STORE_JKS: str = "kafka.ssl.keystore.location"
NODE_OUTPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_KEY_STORE_PASSWORD: str = "kafka.ssl.keystore.password"
NODE_OUTPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_TRUST_STORE_JKS: str = "kafka.ssl.truststore.location"
NODE_OUTPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_TRUST_STORE_PASSWORD: str = "kafka.ssl.truststore.password"
NODE_OUTPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_SSL_KEY_PASSWORD: str = "kafka.ssl.key.password"
NODE_OUTPUT_FORMAT_GEN_OPTIONS_KAFKA_SECRET_STARTING_OFFSET: str = "startingOffsets"
"""
Config Node Constants for Transformer Module
"""
NODE_TRANSFORM_INPUT: str = "input"
NODE_TRANSFORM_CONVERSION: str = "conversion"
NODE_TRANSFORM_CONVERSION_TRANSFORM_TYP: str = "transform_typ"
NODE_TRANSFORM_CONVERSION_TRANSFORM_SEQ: str = "transform_seq"
NODE_TRANSFORM_CONVERSION_TRANSFORM_NAME: str = "transform_name"
NODE_TRANSFORM_CONVERSION_TRANSFORM_QUERY: str = "transform_query"
NODE_TRANSFORM_CONVERSION_TRANSFORM_INPUT: str = "transform_input"
NODE_TRANSFORM_CONVERSION_TRANSFORM_OUTPUT: str = "transform_output"
NODE_TRANSFORM_CONVERSION_TRANSFORM_OUTPUT_TABLE: str = "config_output_table"
NODE_TRANSFORM_OUTPUT: str = "output"
"""
Splunk Metric Executor & Builder Node
"""
NODE_SPLUNK_METRIC_BUILDER: str = "metric_builder"
NODE_SPLUNK_METRIC_CONFIG: str = "metric_config"
NODE_SPLUNK_METRIC_NAMESPACE: str = "namespace"
NODE_SPLUNK_METRIC_CONFIG_METRIC_SET: str = "metric_set"
NODE_SPLUNK_METRIC_CONFIG_METRIC_TYPE: str = "typ"
NODE_SPLUNK_METRIC_CONFIG_METRIC_CUSTOM_METRIC_NAME: str = "custom_metric_name"
NODE_SPLUNK_METRIC_CONFIG_METRIC_MICROBATCH_TIME: str = "microbatch_time"
NODE_SPLUNK_METRIC_CONFIG_METRIC_MICROBATCH_TRANSFORMATION_TIME: str = "microbatch_transformation_time"
NODE_SPLUNK_METRIC_CONFIG_METRIC_MICROBATCH_WRITER_TIME: str = "microbatch_writer_time"
NODE_SPLUNK_METRIC_CONFIG_METRIC_MICROBATCH_WRITER_RECORD_COUNT: str = "microbatch_writer_record_count"
NODE_SPLUNK_METRIC_CONFIG_METRIC_MICROBATCH_RECORD_COUNT: str = "microbatch_record_count"
